import type { ProjectRecord } from "@/domain/project-mapper";

export const projectRecord: ProjectRecord = {
  id: "reved-v1-to-v2",
  name: "RevEd V1 -> RevEd V2",
  mission:
    "Map RevEd V1 features into RevEd V2 without breaking V2 patterns or operator control.",
  status: "Active migration",
  operator: "cash96",
  repositories: [
    {
      id: "repo-a",
      name: "RevEd V1",
      role: "Source",
      provider: "GitHub",
      url: "https://github.com/Revolution-Ed/RevolutionEd.git",
      defaultBranch: "main",
      verifiedStatus: "Readable and shallow-clone verified",
      lastVerifiedAt: "April 20, 2026",
      notes: "Use for source behavior mapping.",
    },
    {
      id: "repo-b",
      name: "RevEd V2",
      role: "Target",
      provider: "GitHub",
      url: "https://github.com/Cash96/Revolution_ed_v2.git",
      defaultBranch: "main",
      verifiedStatus: "Readable and shallow-clone verified",
      lastVerifiedAt: "April 20, 2026",
      notes: "Current implementation source of truth.",
    },
  ],
  doctrine: {
    version: "v0.1 draft",
    approvalState: "Awaiting Approval",
    lastUpdatedAt: "April 20, 2026",
    summary:
      "Protect chat-native orchestration, panel workflows, and anti-page-sprawl migration.",
    criticalRules: [
      "Block task execution when the mapping proposes page-first reconstruction that fights V2's panel-native model.",
      "Treat existing RevEd V2 workflow precedent as the default integration point unless explicitly overridden.",
      "Escalate product-direction ambiguity instead of silently inventing a UX decision.",
    ],
    antiPatterns: [
      "Porting an entire V1 area as a standalone route tree.",
      "Using AI as a generic wrapper rather than as part of the real V2 interaction model.",
      "Running long execution work without task-level history, branch visibility, and review checkpoints.",
    ],
  },
  tasks: [
    {
      id: "clever-onboarding",
      title: "Rebuild Clever integration for student onboarding",
      status: "Proposed",
      sourceFeature: "Student onboarding / Clever sync",
      targetArea: "Student onboarding panels",
      doctrineRisk: "High",
      confidence: "Medium",
      activeBranch: "task/clever-onboarding-attempt-01",
      activeAgents: ["Planner", "Doctrine Guardian"],
      reviewState: "Pending",
      testingState: "Planned",
      latestActivity: "14 minutes ago",
      humanInputNeeded: true,
      sourceUnderstanding: [
        "RevEd V1 uses a page-sequenced onboarding flow with Clever-specific branching logic.",
        "The source flow blends district lookup, roster sync, and student import rules inside one larger onboarding area.",
        "The integration includes operator review points that must survive the migration.",
      ],
      repoBContext: [
        "RevEd V2 already supports student onboarding and uses chat plus contextual panels instead of a long route chain.",
        "Existing onboarding should remain the entry point; Clever should attach as an orchestration capability, not a new app area.",
        "Any district-ready UI needs to feel operational and stable, not startup-hacky.",
      ],
      proposal: [
        "Move Clever sync into the V2 onboarding control panel.",
        "Use chat guidance for edge cases, but keep the primary operational controls visible in panel form.",
        "Block execution until the district sync review moment is clarified with the operator.",
      ],
      openQuestions: [
        "Should district sync confirmation remain a panel action, a chat-confirmed action, or a blended pattern?",
        "Do we need a dedicated exception-handling surface for mismatched roster records?",
      ],
      todo: [
        { id: "t1", label: "Extract V1 Clever flow states and error branches", done: true },
        { id: "t2", label: "Inspect V2 onboarding precedent and panel behavior", done: true },
        { id: "t3", label: "Draft migration proposal and doctrine mapping", done: true },
        { id: "t4", label: "Resolve operator question on district sync confirmation", done: false },
        { id: "t5", label: "Create branch and implementation plan after approval", done: false },
      ],
      timeline: [
        {
          id: "e1",
          timestamp: "08:10",
          actor: "Planner",
          kind: "Analysis",
          summary: "Finished shallow extraction of V1 Clever onboarding touchpoints.",
        },
        {
          id: "e2",
          timestamp: "08:24",
          actor: "Doctrine Guardian",
          kind: "Risk",
          summary: "Flagged page-sprawl risk if Clever flow becomes its own route sequence.",
        },
        {
          id: "e3",
          timestamp: "08:31",
          actor: "Planner",
          kind: "Question",
          summary: "Requested operator guidance on the right confirmation rhythm for district sync.",
        },
      ],
      reviews: [
        {
          reviewer: "Doctrine Guardian",
          status: "Attention Needed",
          summary: "Proposal is directionally correct, but execution must not create a route-heavy exception flow.",
        },
        {
          reviewer: "Product / UX Reviewer",
          status: "Pending",
          summary: "Waiting for approval-ready proposal version.",
        },
      ],
      tests: [
        {
          title: "Onboarding smoke plan",
          status: "Planned",
          summary: "Playwright and human-directed district admin validation prepared, not yet run.",
        },
      ],
    },
    {
      id: "lesson-plan-templates",
      title: "Map lesson plan template setup into teacher workflow",
      status: "Executing",
      sourceFeature: "Lesson plan template setup",
      targetArea: "Teacher lesson planning workspace",
      doctrineRisk: "Medium",
      confidence: "High",
      activeBranch: "task/lesson-plan-templates-attempt-02",
      activeAgents: ["Builder", "Architecture Reviewer"],
      reviewState: "Running",
      testingState: "Running",
      latestActivity: "3 minutes ago",
      humanInputNeeded: false,
      sourceUnderstanding: [
        "V1 stores template setup as a separate configuration-heavy flow.",
        "Teachers need to reuse template structures without entering an admin-feeling page.",
      ],
      repoBContext: [
        "V2 already supports lesson planning in a blended chat plus panel workspace.",
        "The mapped behavior should likely live as a contextual template assistant inside the existing flow.",
      ],
      proposal: [
        "Add template setup inside lesson planning.",
        "Keep chat available for fast generation, but let teachers inspect and adjust template metadata in UI.",
      ],
      openQuestions: [],
      todo: [
        { id: "t1", label: "Extract template fields from V1", done: true },
        { id: "t2", label: "Map fields into V2 lesson planning panels", done: true },
        { id: "t3", label: "Build branch attempt two after operator revision", done: true },
        { id: "t4", label: "Run architecture and UX review", done: false },
        { id: "t5", label: "Execute regression and scenario tests", done: false },
      ],
      timeline: [
        {
          id: "e1",
          timestamp: "07:42",
          actor: "Builder",
          kind: "Branch",
          summary: "Created fresh attempt after retry guidance from operator.",
        },
        {
          id: "e2",
          timestamp: "08:02",
          actor: "Builder",
          kind: "Execution",
          summary: "Implemented panel-first template setup inside lesson planning workflow.",
        },
        {
          id: "e3",
          timestamp: "08:38",
          actor: "Architecture Reviewer",
          kind: "Review",
          summary: "Review running on updated branch against existing workspace patterns.",
        },
      ],
      reviews: [
        {
          reviewer: "Architecture Reviewer",
          status: "Running",
          summary: "Evaluating code shape and fit with existing lesson planning modules.",
        },
        {
          reviewer: "QA / Test Interpreter",
          status: "Running",
          summary: "Interpreting current Playwright artifacts and screenshots.",
        },
      ],
      tests: [
        {
          title: "Teacher template flow",
          status: "Running",
          summary: "Automated route plus panel regression is in flight.",
        },
      ],
    },
    {
      id: "dsh-curriculum-investigation",
      title: "Investigate DSH partnership curriculum mapping",
      status: "Ready to Merge",
      sourceFeature: "DSH partnership curriculum pages",
      targetArea: "Curriculum orchestration panels",
      doctrineRisk: "Low",
      confidence: "High",
      activeBranch: "task/dsh-curriculum-attempt-01",
      activeAgents: ["Planner", "QA / Test Interpreter"],
      reviewState: "Passed",
      testingState: "Passed",
      latestActivity: "31 minutes ago",
      humanInputNeeded: false,
      sourceUnderstanding: [
        "The source area is mostly a content presentation cluster with partnership-specific metadata.",
        "The real migration value is content access and contextual navigation, not the original page shell.",
      ],
      repoBContext: [
        "V2 already has curriculum and content structures that can absorb the feature.",
        "The best fit is a contextual curriculum panel stack rather than a separate public page system.",
      ],
      proposal: [
        "Map DSH content into existing curriculum panels.",
        "Document why the original public-page shell was intentionally not recreated.",
      ],
      openQuestions: [],
      todo: [
        { id: "t1", label: "Inspect DSH source flows", done: true },
        { id: "t2", label: "Map to V2 curriculum structures", done: true },
        { id: "t3", label: "Run doctrine, UX, and QA review", done: true },
        { id: "t4", label: "Prepare merge report", done: true },
      ],
      timeline: [
        {
          id: "e1",
          timestamp: "06:58",
          actor: "Planner",
          kind: "Proposal",
          summary: "Submitted mapping plan with anti-page-sprawl rationale.",
        },
        {
          id: "e2",
          timestamp: "07:49",
          actor: "Doctrine Guardian",
          kind: "Review",
          summary: "Approved the plan as consistent with V2 architecture and interaction model.",
        },
        {
          id: "e3",
          timestamp: "08:11",
          actor: "QA / Test Interpreter",
          kind: "Testing",
          summary: "Reported a clean pass with no new operator-facing friction.",
        },
      ],
      reviews: [
        {
          reviewer: "Doctrine Guardian",
          status: "Passed",
          summary: "No V1 structural drift detected.",
        },
        {
          reviewer: "Product / UX Reviewer",
          status: "Passed",
          summary: "The mapped behavior feels native to V2 instead of retrofitted.",
        },
      ],
      tests: [
        {
          title: "Curriculum panel smoke test",
          status: "Passed",
          summary: "Automated and human-directed test plan passed with stable screenshots.",
        },
      ],
    },
  ],
  approvals: [
    {
      id: "a1",
      kind: "Doctrine Approval",
      priority: "High",
      title: "Approve RevEd V2 doctrine draft",
      summary: "Execution stays blocked until doctrine is approved.",
      status: "Open",
      approveLabel: "Approve doctrine",
      revisionLabel: "Keep in draft",
      target: {
        entity: "doctrine",
      },
    },
    {
      id: "a2",
      kind: "Task Question",
      priority: "High",
      title: "Resolve Clever district sync confirmation rhythm",
      summary: "Planner needs a product decision before branching.",
      status: "Open",
      approveLabel: "Approve proposed rhythm",
      revisionLabel: "Send back for revision",
      target: {
        entity: "task",
        taskId: "clever-onboarding",
        approveTaskStatus: "Approved",
        revisionTaskStatus: "Needs Revision",
        clearHumanInputOnApprove: true,
        clearOpenQuestionsOnApprove: true,
        humanInputNeededOnRevision: true,
        reviewStateOnApprove: "Pending",
        reviewStateOnRevision: "Attention Needed",
      },
    },
    {
      id: "a3",
      kind: "Merge Approval",
      priority: "Medium",
      title: "Review DSH curriculum merge packet",
      summary: "Review passed. Awaiting merge decision.",
      status: "Open",
      approveLabel: "Approve merge",
      revisionLabel: "Return to work",
      target: {
        entity: "task",
        taskId: "dsh-curriculum-investigation",
        approveTaskStatus: "Merged",
        revisionTaskStatus: "Needs Revision",
        clearHumanInputOnApprove: true,
        humanInputNeededOnRevision: true,
        reviewStateOnApprove: "Passed",
        reviewStateOnRevision: "Attention Needed",
      },
    },
  ],
  strategicNotes: [
    {
      id: "s1",
      title: "Protect the V2 blend",
      emphasis: "High signal",
      summary: "Keep direct UI work and AI-assisted work tightly connected.",
    },
    {
      id: "s2",
      title: "Avoid page-based drift",
      emphasis: "Doctrine-critical",
      summary: "Extend existing flows instead of recreating V1 route sprawl.",
    },
  ],
  reports: [
    {
      id: "r1",
      title: "Overnight progress summary",
      type: "Overnight Summary",
      summary: "One task is merge-ready, one is in execution, and one question is still open.",
      timestamp: "Today 08:40",
    },
    {
      id: "r2",
      title: "DSH curriculum review packet",
      type: "Merge Summary",
      summary: "Mapping decision, review result, and follow-up notes.",
      timestamp: "Today 08:18",
    },
  ],
  testScenarios: [
    {
      id: "ts1",
      name: "Admin Clever onboarding",
      role: "District admin",
      purpose: "Validate district roster sync into student provisioning.",
      startPoint: "/onboarding",
      checkpoints: [
        "Enter district context",
        "Trigger Clever sync",
        "Confirm imported student roster summary",
      ],
    },
    {
      id: "ts2",
      name: "Teacher lesson plan generation",
      role: "Teacher",
      purpose: "Validate template setup and AI assistance in lesson planning.",
      startPoint: "/lesson-planning",
      checkpoints: [
        "Open lesson planning workspace",
        "Apply template setup",
        "Generate child artifact and inspect output",
      ],
    },
  ],
};